image: node:latest

services:   
  - mysql:latest

cache:   
  paths:  
    - node_modules/
    - data/
    - log/
    - upload/

before_script:
  - npm install --production

deploy_job:
  stage: deploy
  only:
    - master
  script:
    - echo "ok"